version: '3.7'
services:
  apache:
    image: 'canelrom1/apache2:latest'
    #build:
    #  context: ./src
    container_name: apache
    ports:
      - '80:80'
    #volumes:
      #- ./src/entrypoint.sh:/entrypoint.sh
    environment:
      - 'APACHE_HTACCESS=0'

# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
