version: '3.7'
services:
  apache:
    image: 'canelrom1/apache2:latest'
    #build:
    #  context: ./src
    container_name: apache2
    #restart: on-failure
    networks:
      - traefik_wan
    environment:
      - 'APACHE_HTACCESS=1'
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:localhost"
      - "traefik.port=80"
      - "traefik.docker.network=traefik_wan"

networks:
  traefik_wan:
    external: true

# vim: ft=yaml tw=80 et ts=2 sw=2 sts=2
